version: '3'
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: redmine
      MYSQL_DATABASE: redmine
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --sql_mode=""
  web:
    build:
      context: .
      args:
        #redmine_version: $redmine_version
        redmine_database: mysql
    entrypoint: ["/tmp/redmine/plugins/redmine_issue_badge/script/start-server.sh"]
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    environment:
      RAILS_ENV: development
    volumes:
      - .:/tmp/redmine/plugins/redmine_issue_badge
    ports:
      - "3000:3000"
    links:
      - db
    depends_on:
      - db
